### PR TITLE
chmod +x gradlew for mac and linux

### PR DESCRIPTION
**Pull request by bombcar**
this may be where they're coming from ...

### CODE REVIEW

**Comment by SinTh0r4s** [comment]
@TheElan

**Comment by TheElan** [comment]
chmod +x basically marks things as executable (e.g. scripts, binaries) on unix systems.

that's odd, I was having the impression that it was already allowed to execute...

Probably we can remove chmod +x step from workflows now

**Comment by TheElan** [comment]
Looks fine to me - would merge

**Comment by bombcar** [comment]
A chmod +x isn’t noticed by git unless you do trickery sometimes, so even if it ram it may not “take”. 

`git update-index --chmod=+x path/to/file`

most git GUIs handle this for you.

**Pull request merged**
